### ISSUE TITLE
action updates devtools store properly but doesn't re-render with the correct state

### ISSUE THREAD

**Issue by andre0799** [gaearon/redux-thunk#30]
so on my component I call this  ``` dispatch(actions.createExercise(planId))  ``` 

which calls this action creator

```javascript 
export function createExercise(id) {
  return dispatch => {
    console.log('createExercise')
    const exerciseId = uuid();

    dispatch({
        type: 'CREATE_EXERCISE',
        id: exerciseId,
        exercise: {
          title: 'CREATE_EXERCISE',
          id: exerciseId
        }
      });

    return function(){
      dispatch({
          type: 'ADD_EXERCISE_TO_PLAN',
          id,
          exerciseId
        });
    }
  };
} 

 ``` 

and this are the reducers (only pasted the relevant parts of the code)

```javascript 
const plans = (state = {}, action) => {
  switch (action.type) {
  case 'ADD_EXERCISE_TO_PLAN':
    console.log(action.type)
    return {
      ...state,
      [action.id]: {
        ...state[action.id],
        exercises: [
          ...state[action.id].exercises,
          ...action.exerciseId
        ]
      }
    };  

}


const exercises = (state = {}, action) =>  {
  switch (action.type) { 

  case 'CREATE_EXERCISE':
    return {
      ...state,
      [action.id]: {
        ...action.exercise
      }
    }; 

}
``` 

As you can see on the screenshot below the actions were properly called, but the state wasn't properly updated on the component. The printed state (which was printed on the render method) doesn't contain the updated state, neither the exercise was added to the entities object nor the exerciseId was added to the exercises array on the Plan object

![image](https://cloud.githubusercontent.com/assets/5369270/10956734/ad5958cc-833c-11e5-8c24-ffa77357e56e.png)

but if you see on the dev tools, both objects are correct... Thanks in advance, any help is appreciated

![image](https://cloud.githubusercontent.com/assets/5369270/10956700/7877c440-833c-11e5-96cd-c93f17d1e6a0.png)

![image](https://cloud.githubusercontent.com/assets/5369270/10956704/7fd7ae30-833c-11e5-9580-6d074eac07ac.png)

**Comment by gaearon** [comment]
It's hard to say what the exact problem is because there are several deeper problems in [your example app](https://github.com/andre0799/workoutTable-redux-experiment/tree/master):

* You're [mixing `dispatch` with `bindActionCreators` when they're supposed to be used exclusively](https://github.com/gaearon/redux-thunk/issues/29#issuecomment-154162186)
* The `excercize.js` component in your project copies its props to state in the constructor for a reason I don't understand.

Please fix these two issues, update the project, and if you still have problems, I can take another look. In the future, please avoid asking questions as issues in Redux Thunk repo, as your questions are not related to it. It's best to ask for help on StackOverflow.

**Comment by andre0799** [comment]
I'll do. Thanks
