### ISSUE TITLE
receive action type,payload in component level

### ISSUE THREAD

**Issue by faysal515** [gaearon/redux-thunk#96]
My use case is fairly simple. I'm inserting lets say `food`. Depending on the dispatch, I want to show toastr notification & in cases redirect to another page also.
 Whenever I'm calling an asynchronous api through redux thunk, I can dispatch multiple from a single action . the problem is I cannot return the dispatch object in component level. for which I have no clue in component level which dispatch was actually fired. Thus i'm using a hacky way to accomplish this. I'm looking for a more appropriate and non-bloated answer. And also interested to know if i'm doing in the proper `redux` way.  Please take a look on my workaround gist.

https://gist.github.com/faysal515/847e69e73ccf4574a099cda83ce0030b

**Comment by faysal515** [comment]
@gaearon any thought on that?

**Comment by gaearon** [comment]
You can return anything from your action creator, including that Promise. Instead of `cb(null,response.data);` you can `return response.data`, and that will become the resolved value of your Promise. Then in the component you can write `this.props.createFood(food).then(data => ...)`.

Note that `.then(...).catch(...)` will make any errors in components go to your `catch()` method and put React into an inconsistent state. I suggest using `.then(onSuccess, onReject)` instead for dispatches.
